### ISSUE TITLE
error while rexecuting python3 tbw.py

### ISSUE THREAD

**Issue by amolmt** [galperins4/tbw#28] opened 2018-06-24 17:06 UTC
I am getting the following error while executing tbw.py from core_v1 dir
and I am using this script for LWF node
here's the error:

python3 tbw.py 
Traceback (most recent call last):
  File "tbw.py", line 435, in <module>
    username = get_dbname()
  File "tbw.py", line 417, in get_dbname
    uname = network[data['network']]['db_user']
KeyError: 'network'

**Comment by galperins4** [comment] 2018-06-25 02:41
Usually this is caused by having the network incorrect in the config.json file. What is the parameter you have specified in config.json for network?

**Comment by galperins4** [comment] 2019-09-16 02:23
Closed as lwf is no longer supported

**Closed by galperins4** 2019-09-16 02:23 UTC
