### ISSUE TITLE
I get an error when running tbw.py.

### ISSUE THREAD

**Issue by bluetaeyang** [galperins4/tbw#32] opened 2018-09-17 05:30 UTC
Traceback (most recent call last):
  File "tbw.py", line 443, in <module>
    arkdb = ArkDB(network[data['network']]['db'], username, network[data['network']]['db_pw'], data['publicKey'])
  File "/home/amis5818/tbw/core_v1/snek/ark.py", line 10, in __init__
    port='5432'
  File "/home/amis5818/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
------------------------------------
I get this error.
What's wrong?

**Comment by bluetaeyang** [comment] 2018-09-17 05:31
node ip = 192.168.0.126
tbw ip = 192.168.0.11

**Comment by galperins4** [comment] 2018-09-17 13:55
@bluetaeyng I'm assuming the issue is you aren't running a relay node on the tbw server hence why it can't find the postgresql server. A relay is required at the current time to run tbw.

**Comment by bluetaeyang** [comment] 2018-09-19 00:36
I did not lay a node. It is my mistake.
After installing the node, another error appears.
If you hit pm2 log, it is part of the screen.
------------------------------------------------------------

[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/amis5818/.pm2/pm2.log last 15 lines:
PM2        | [2018-09-19T09:29:40.863Z] PM2 log: App name:pool id:2 online
PM2        | [2018-09-19T09:29:41.413Z] PM2 log: App [pool] with id [2] and pid [26987], exited with code [1] via signal [SIGINT]
PM2        | [2018-09-19T09:29:41.415Z] PM2 log: Starting execution sequence in -fork mode- for app name:pool id:2
PM2        | [2018-09-19T09:29:41.422Z] PM2 log: App name:pool id:2 online
PM2        | [2018-09-19T09:29:41.984Z] PM2 log: App [pool] with id [2] and pid [26993], exited with code [1] via signal [SIGINT]
PM2        | [2018-09-19T09:29:41.987Z] PM2 log: Starting execution sequence in -fork mode- for app name:pool id:2
PM2        | [2018-09-19T09:29:41.994Z] PM2 log: App name:pool id:2 online
PM2        | [2018-09-19T09:29:42.552Z] PM2 log: App [pool] with id [2] and pid [26999], exited with code [1] via signal [SIGINT]
PM2        | [2018-09-19T09:29:42.555Z] PM2 log: Starting execution sequence in -fork mode- for app name:pool id:2
PM2        | [2018-09-19T09:29:42.562Z] PM2 log: App name:pool id:2 online
PM2        | [2018-09-19T09:29:43.100Z] PM2 log: App [pool] with id [2] and pid [27005], exited with code [1] via signal [SIGINT]
PM2        | [2018-09-19T09:29:43.103Z] PM2 log: Starting execution sequence in -fork mode- for app name:pool id:2
PM2        | [2018-09-19T09:29:43.110Z] PM2 log: App name:pool id:2 online
PM2        | [2018-09-19T09:29:43.850Z] PM2 log: App [pool] with id [2] and pid [27017], exited with code [1] via signal [SIGINT]
PM2        | [2018-09-19T09:29:43.851Z] PM2 log: Script /home/amis5818/tbw/core_v1/pool.py had too many unstable restarts (16). Stopped. "errored"

/home/amis5818/.pm2/logs/pool-out-2.log last 15 lines:
/home/amis5818/lwf-node/logs/lwfcoin-err.log last 15 lines:
3|lwf-node | NOTICE:  function round_fees_insert() does not exist, skipping
3|lwf-node | NOTICE:  Calculating fees for rounds, please wait...
3|lwf-node | NOTICE:  relation "mem_accounts" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts_balance" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_round" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_round_address" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_round_round" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2delegates" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2delegates_accountId" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2u_delegates" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2u_delegates_accountId" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2multisignatures" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2multisignatures_accountId" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2u_multisignatures" already exists, skipping
3|lwf-node | NOTICE:  relation "mem_accounts2u_multisignatures_accountId" already exists, skipping

/home/amis5818/tbw/core_v1/output/pay-1.log last 15 lines:
1|pay      | 2018-09-19 06:12 +09:00: peers: 53
1|pay      | filtered peers 47
1|pay      | 2018-09-19 06:13 +09:00: Payment Run Completed!
1|pay      | 2018-09-19 09:15 +09:00: peers: 53
1|pay      | filtered peers 46
1|pay      | 2018-09-19 09:16 +09:00: Payment Run Completed!

/home/amis5818/tbw/core_v1/output/tbw-0.log last 15 lines:
0|tbw      | 2018-09-19 09:24 +09:00: Processed Block: 1589706
0|tbw      |
0|tbw      |     Voters processed: 1
0|tbw      |     Total Approval: 32900338805842
0|tbw      |     Voters Rewards: 250000000
0|tbw      |     Delegate Reward: 250000000
0|tbw      |     Voter + Delegate Rewards: 500000000
0|tbw      |     Total Block Rewards: 500000000
0|tbw      | 2018-09-19 09:24 +09:00:
0|tbw      |
0|tbw      | Current block count : 507
0|tbw      | 2018-09-19 09:24 +09:00:
0|tbw      | Waiting for the next block....
0|tbw      |

/home/amis5818/.pm2/logs/tbw-error-0.log last 15 lines:
0|tbw      | psycopg2.OperationalError: FATAL:  password authentication failed for user "lwf"
0|tbw      | FATAL:  password authentication failed for user "lwf"
0|tbw      |
0|tbw      | 2018-09-19 06:13 +09:00: Traceback (most recent call last):
0|tbw      |   File "/home/amis5818/tbw/core_v1/tbw.py", line 493, in <module>
0|tbw      |     time.sleep(data["block_check"])
0|tbw      | KeyboardInterrupt
0|tbw      | 2018-09-19 09:28 +09:00: Traceback (most recent call last):
0|tbw      |   File "/home/amis5818/tbw/core_v1/tbw.py", line 493, in <module>
0|tbw      |     time.sleep(data["block_check"])
0|tbw      | KeyboardInterrupt
0|tbw      | 2018-09-19 09:29 +09:00: Traceback (most recent call last):
0|tbw      |   File "/home/amis5818/tbw/core_v1/tbw.py", line 493, in <module>
0|tbw      |     time.sleep(data["block_check"])
0|tbw      | KeyboardInterrupt

/home/amis5818/.pm2/logs/pay-error-1.log last 15 lines:
1|pay      |   File "/home/amis5818/tbw/core_v1/snek/snek.py", line 118, in stagedLiskPayment
1|pay      |     return self.cursor.execute("SELECT rowid, * FROM staging WHERE processed_at IS NULL LIMIT 20")
1|pay      | sqlite3.OperationalError: no such table: staging
1|pay      | 2018-09-19 06:13 +09:00: Traceback (most recent call last):
1|pay      |   File "/home/amis5818/tbw/core_v1/pay.py", line 173, in <module>
1|pay      | 2018-09-19 06:13 +09:00:     time.sleep(300)
1|pay      | KeyboardInterrupt
1|pay      | 2018-09-19 09:28 +09:00: Traceback (most recent call last):
1|pay      |   File "/home/amis5818/tbw/core_v1/pay.py", line 176, in <module>
1|pay      | 2018-09-19 09:28 +09:00:     time.sleep(300)
1|pay      | KeyboardInterrupt
1|pay      | 2018-09-19 09:29 +09:00: Traceback (most recent call last):
1|pay      |   File "/home/amis5818/tbw/core_v1/pay.py", line 176, in <module>
1|pay      |     time.sleep(300)
1|pay      | KeyboardInterrupt

/home/amis5818/.pm2/logs/pool-error-2.log last 15 lines:
2|pool     | 2018-09-19 09:29 +09:00:   File "/home/amis5818/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
2|pool     | 2018-09-19 09:29 +09:00:     inner()
2|pool     | 2018-09-19 09:29 +09:00:   File "/home/amis5818/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 774, in inner
2|pool     | 2018-09-19 09:29 +09:00:     fd=fd)
2|pool     | 2018-09-19 09:29 +09:00:   File "/home/amis5818/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 666, in make_server
2|pool     | 2018-09-19 09:29 +09:00:     passthrough_errors, ssl_context, fd=fd)
2|pool     | 2018-09-19 09:29 +09:00:   File "/home/amis5818/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 577, in __init__
2|pool     | 2018-09-19 09:29 +09:00:     self.address_family), handler)
2|pool     |   File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
2|pool     | 2018-09-19 09:29 +09:00:     self.server_bind()
2|pool     |   File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
2|pool     | 2018-09-19 09:29 +09:00:     socketserver.TCPServer.server_bind(self)
2|pool     |   File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
2|pool     | 2018-09-19 09:29 +09:00:     self.socket.bind(self.server_address)
2|pool     | 2018-09-19 09:29 +09:00: OSError: [Errno 99] Cannot assign requested address

-----------------------------------------------------------
By the way, payment seems to be doing well.
What's wrong with the code above?

**Comment by galperins4** [comment] 2018-09-19 00:48
Are you in the lwf discord? If so can you let me know your screen name as it would be easier to chat there

**Comment by bluetaeyang** [comment] 2018-09-19 05:44
모나미블루#3328

**Comment by prologueyan-hr** [comment] 2019-05-18 06:28
2|pool | 2018-09-19 09:29 +09:00: self.socket.bind(self.server_address)
2|pool | 2018-09-19 09:29 +09:00: OSError: [Errno 99] Cannot assign requested address
have u solved this？

**Comment by galperins4** [comment] 2019-05-18 13:01
Need more information @prologueyan. What network are you getting that error on?

**Comment by prologueyan-hr** [comment] 2019-05-20 06:01
@galperins4  Thanks.I solved that

**Comment by galperins4** [comment] 2019-09-16 02:22
Closing as it appears solved

**Closed as completed by galperins4** 2019-09-16 02:22 UTC
